#
# N.B.: docker compose must be invoked from the project root directory:
#
# docker compose -f path/to/compose.yaml up --exit-code-from cantaloupe
#
services:
  cantaloupe:
    platform: linux/amd64
    build:
      context: ../../../
      dockerfile: $PWD/docker/ubuntu/jammy/Dockerfile
    ports:
      - "8182:8182"  
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: MinioUser
      MINIO_SECRET_KEY: OpenSesame
    hostname: minio
    command: server /data
  redis:
    image: redis:alpine
    hostname: redis
